lib/resend/email.ts
package.json
pages/api/admin/artwork-email.ts
pages/api/cron/show-submission-email.ts
yarn.lock

This fix's the bug with emails exceeding the [API rate limit on resend](https://resend.com/changelog/api-rate-limit) of 10 emails per second.

Fix email rate limit bug.

---

lib/contentful/pages/news.ts

This fixes a bug with related news articles causing 500 errors when preview articles. related articles are now always not in preview mode to prevent articles being fetched that do not have the correct info (a missing image for example).

Bugfix related news articles 500 error

---

lib/resend/email.ts
lib/slack.ts
pages/api/admin/artwork-email.ts

This moves error message into their own slack channel as to not clutter up content channel with info that is not relevant for most people in that channel.

move email errors to error channel on slack

---

components/submission/showSubmissionForm.tsx
components/submission/showSubmissionStep3.tsx
lib/resend/email.ts
pages/api/show-submission-v2.ts
types/shared.d.ts
util.ts

- Update the reply to email address on show emails.
- Add required new field to new artist on submission form.
- Lowercase 'with' on coming soon section.

Feature updates aug

---

components/showPreview.tsx
components/upcomingShowPreview.tsx
lib/contentful/client.ts
lib/contentful/pages/artists.ts
lib/contentful/pages/radio.ts
pages/submission-v2.tsx
util.ts
views/radio/showBody.tsx

Merging recent bugfixes from main for deployment

Merge recent changes from main

---

lib/contentful/client.ts
lib/contentful/pages/radio.ts
pages/radio/[slug].tsx
views/radio/showBody.tsx

This allows show pages to only have a title field and adds a placeholder image on the slug page.

allow show page to only have title field

---

util.ts

This fixes a bug with a published show containing unpublished artists that are being returned by contentful.

remove null artists who are unpublished on a published show

---

components/eventRow.tsx
pages/events/index.tsx
types/shared.d.ts

This implements adding film screenings as an event type and reorders the event page columns to a more logical order for improved UI/UX.

Feature film screenings

---

components/livePlayer.tsx
components/upcomingShowPreview.tsx
views/radio/showBody.tsx

This implements a fix for a bug when contentful returns null objects for draft artists within a published show page.

Bugfix draft artists

---

pages/api/schedule-artwork.tsx

This implements fixes for longer schedules displaying correctly on the daily schedule generator.

Bugfix long schedule

---

hooks/useArtistsGuests.ts
hooks/useNewsArticles.ts
hooks/useRadioShows.ts
lib/contentful/pages/artists.ts
views/news/allArticles.tsx
views/radio/allShows.tsx

This PR fixes a issue with guests and news pages having the same key for fetching new data using useSWRInfinite. It also adds nice load more animation to news page and fixes bug when loading and load more would appear at the same time when filtering shows by genre.

bugfix same key for fetch with guests and news page

---

emails/showSubmission.tsx

This PR fixes a typo in the show confirmation email and removes use of exclamation marks.

fix typo in show submission email

---

lib/contentful/client.ts
types/contentful.ts
types/shared.d.ts

This PR fixes bug in show by timestamp endpoint where it doesn't return show artwork required for sc upload. It also moves to using preview client to ensure draft shows are also returned.

show by timestamp endpoint updates

---

lib/loaders.ts

This PR fixes image cropping of show pages to be set to 16:9 aspect ratio with a focal point set of faces using Contentfuls image API. Now means we dont need to individually crop images on contentful and makes the show images more flexible more multiple formats like show artwork.

Fix image cropping

---

components/submission/showSubmissionForm.tsx

This PR add validation to show form that show names can be max 35 characters long.
This is to ensure they can be displayed nicely on show and daily schedule artworks.

Show name max character length

---

lib/contentful/calendar.ts

This fixes bug where some insta handles would appear for the following day when the show was around midnight.

Bugfix weekly insta handles for shows around midnight

---

lib/contentful/pages/events.ts

Fix bug where no image on a featured event would cause the site deployment to fail. Now preview image is shown instead.

Bugfix no image on featured event

---

components/formFields/imageUploadField.tsx
pages/api/revalidate/show-artwork.ts

- Reduce max image size to 2MB on show submission form as larger images occasionally cause problems with the artwork regeneration.
- Throw error from show artwork regeneration if artists is undefined.

Show artwork updates

---

constants.ts
pages/api/cron/artwork-email.ts
pages/api/cron/show-submission-email.ts

This fixes bug with hiting the rate limit on sending emails using resend api.

increase rate limit on resend api calls

---

styles/globals.css

This makes links in prose a regular font weight of 300, improving readability when an article has a lots of links.

Links in prose regular weight

---

pages/api/revalidate/radio.ts

This PR fixes bug where artists pages did not include a newly published show without the user refreshing the page. To fix this we know revalidate all artist pages associated with a show when ISR webhook is sent to the API.

Bugfix Revalidating shows and linked artists

---

hooks/useSchedule.ts
pages/api/schedule.ts
views/home/nextUp.tsx

This PR attempts to fix bug where live now is not updated when a tab is inactive for a long period of time. Schedule API is polled when tab is in the background and stale data must be revalidated.

Bugfix schedule cache issue

---

hooks/useSchedule.ts
pages/api/schedule.ts

This PR reverts cache changes in the schedule API header. Initially attempting to solve issues with live now banner not updating after a tab is inactive for a long period of time. However I think that issue might be caused by supabase log in rather than the API cache settings themselves.

Revert API schedule header
