Refuge-Worldwide/refuge-worldwide

hooks/useArtistRoleFilter.ts
hooks/useArtistsGuests.ts
lib/contentful/pages/artists.ts
lib/contentful/pages/rss.ts
pages/api/revalidate/artists.ts
pages/artists/guests.tsx
pages/artists/index.tsx
util.ts

- Refactor to adding in guests page
- Update rss feed size

improve artists page

---

lib/contentful/pages/radio.ts

- added check for duplicates in related shows query

Removed duplicated shows from "More episodes" section

---

components/badge.tsx
components/genresList.tsx
hooks/useGenreFilter.ts
hooks/useRadioShows.ts
icons/cross.tsx
lib/contentful/client.ts
pages/api/shows.ts
pages/radio/index.tsx
styles/genreList.css
styles/globals.css
views/radio/allShows.tsx
yarn.lock

- New genre filter design
- Genre sidebar added
- Searchable genres
- Loading indicator while fetching filtered shows
- Started implementing selection of multiple genres

Phase 1 of new genre filter/search 

---

components/showSubmissionForm.tsx
components/showSubmissionStep3.tsx
pages/api/show-submission.ts
types/shared.d.ts

- improving list and instagram regex
- pre-record file upload now always visible

Submission form improvements

---

pages/api/schedule.ts

Adding image of live now show from contentful

Schedule api updates

---

components/genresList.tsx
lib/contentful/client.ts
views/radio/showBody.tsx

Improving genre filter search so it searches through last 999 shows for a given genre. To be move over to seperate search platform like algolia in future.

Show genre filter

---

components/formFields/imageUploadField.tsx
components/showSubmissionForm.tsx
components/showSubmissionStep1.tsx
components/showSubmissionStep3.tsx
pages/api/show-submission.ts
styles/globals.css
types/shared.d.ts

Reverts mirshko/refuge-worldwide#65

Revert "Submission form multiple images"

---

components/livePlayer.tsx
hooks/useSchedule.ts
lib/contentful/schedule.ts
pages/api/schedule.ts
views/home/nextUp.tsx

Fix client side errors appearing when error on schedule api route

Fix schedule error

---

next.config.js

add scrollrestoration flag to config to preserve scroll position on navigation

preserve scroll position on navigation

---

hooks/usePlayerState.ts

Couldn't test it as I don't have the Contentful env vars - should fix the problem though

Pause livestream when Soundcloud show activated

---

pages/chat.tsx

Temporary revert until working solution is found.

revert chatroom height to previous vales on mobile

---

lib/contentful/search.ts
package.json
pages/search.tsx
yarn.lock

Return 20 results from each type, improve loading state and make search url encoded so you can return to your search term when using back button or copy the link for a specific search term.

Hotfix more search results

---

components/mixcloudPlayer.tsx

change url src for mixcloud to new widget url `https://player-widget.mixcloud.com/widget/iframe/?`

Fix mixcloud player

---

pages/search.tsx

Improve search accessibility:
- Add in search results header with wording: “Results for {search term}”
- Move focus to search header when pressing enter.
- Let screen reader know when no results have been found.
- Let screen reader know results appear as you type.
- Improve placeholder so you know what you can search for.

Feature search accessibility improvements

---

lib/rich-text.tsx
pages/news/[slug].tsx
pages/news/index.tsx

Embed youtube and tally iframes into articles and text fields.

Feature embed youtube and tally

---

lib/contentful/calendar.ts
pages/admin/calendar.tsx

Fix bugs around status being removed on show save + adjust colour of TBC show to light grey so its not so intense!

Bugfix admin calendar

---

components/submission/showSubmissionStep3.tsx
emails/showSubmission.tsx
pages/api/show-submission-email.ts
pages/api/show-submission-v2.ts
pages/submission-v2.tsx
types/shared.d.ts
vercel.json

Improve show submission emails and fix bugs in submission process.

Bugfix show submission emails

---

components/showSubmissionForm.tsx
components/showSubmissionStep3.tsx
components/submission/showSubmissionForm.tsx
components/submission/showSubmissionStep3.tsx
pages/submission-v2.tsx
pages/submission.tsx

Move to async artist dropdowns for submission forms.

Async artist dropdowns

---

emails/showSubmission.tsx
lib/contentful/calendar.ts
lib/resend/email.ts
pages/admin/calendar.tsx
pages/api/admin/artist-email.ts
pages/api/admin/calendar-show.ts
pages/api/admin/confirmation-email.ts
pages/api/calendar.ts
pages/api/show-submission-email.ts
pages/api/show-submission-v2.ts
views/admin/emailModal.tsx

Calendar improvements:
- better error handling
- remove booker
- add pre-rec pill to show preview
- move crud code to server side for easier logging

Calendar improvements

---

components/formFields/artistsMultiSelectField.tsx
lib/contentful/search.ts
pages/admin/calendar.tsx
pages/api/artist-search.ts

Create artist dropdown api endpoint outside of protected admin routes for submission form.

fix bug in artist dropdown for submission form

---

lib/contentful/schedule.ts

Fix CET adjustment so it resolves automatically.

CET adjustment fix

---

lib/contentful/pages/radio.ts
views/radio/nextShows.tsx

- Remove shows automatically from orange section if they are tomorrow or before.

Orange section auto remove old shows

---

pages/news/[slug].tsx
views/news/articleBody.tsx

Add archive link to bottom of berlin stories and icymi news articles.

Feature icymi bs archive link

---

lib/rich-text.tsx
pages/about.tsx
pages/access.tsx
pages/imprint.tsx
pages/values.tsx
pages/workshops/[slug].tsx
pages/workshops/carhartt-wip-tour.tsx
views/artists/artistBody.tsx
views/news/articleBody.tsx

Changing tally embedded form to be responsive height. Fixing issues with white spaces in articles around embed.

Bugfix tally form height

---

lib/contentful/calendar.ts
pages/admin/calendar.tsx

No longer required to add show title when creating a new show in the calendar.

Bugfix show title not required

---

emails/showArtwork.tsx
lib/contentful/pages/radio.ts
lib/resend/email.ts
pages/admin/calendar.tsx
pages/api/admin/artwork-email.ts
styles/globals.css
views/admin/calendarSearch.tsx
views/admin/showArtworkModal.tsx

Add show artwork email to admin calendar.

Feature show artwork email

---

lib/contentful/pages/radio.ts
pages/api/admin/artwork-email.ts

Fix bug with submission emails being sent to those who have already submitted.

Bugfix submittion emails

---

lib/contentful/pages/home.ts
views/home/latestNews.tsx

Only show one **Berlin stories** and **ICYMI** article in the latest news section on the homepage.

Homepage latest news - one BS/ICYMI

---

lib/contentful/calendar.ts
views/admin/emailModal.tsx

This fixes bug with validating email field in admin calendar to ensure a array of emails is sent to contentful.

validate emails correctly in email modal

---

components/livePlayer.tsx

This fix bugs with schedule icon being too small on mobile and channel 2 live now title not updating alongside api.

fix ch2 schedule icon and marquee key

---

pages/api/automated-artwork.tsx
pages/api/show-submission-v2.ts

This fixes bug with last artist names not being separated by & and also adds background colours for day of the month.

fix artist name bug fix and add in colours for day of the month

---

components/formFields/artistsMultiSelectField.tsx
lib/contentful/search.ts
pages/admin/calendar.tsx
pages/api/admin/search.ts

This adds draft status to artist dropdown in the admin calendar.

show draft status in artist dropdown in calendar

---

components/Prose/Prose.tsx
components/eventRow.tsx
lib/contentful/fragments.ts
styles/globals.css
types/shared.d.ts
views/events/featuredEvents.tsx

This implements updates to events page including:
- details summary element to shown more info in expandable element
- event description directly on event page
- time of event
- entry / ticket price

Features event page updates

---

pages/api/schedule-artwork.tsx

This implements a fix for times in daily artwork generator being in GMT rather than CET.

fix bug with daily artwork generator times

---

pages/admin/daily-schedule-generator.tsx

This implements a loading state for the daily artwork generator.

add loading state to daily artwork generator

---

pages/admin/calendar.tsx
views/admin/additionalMenu.tsx
views/admin/calendarInsta.tsx

This PR makes the additional menu in the admin calendar available for mobile so that our team can access the daily schedule artwork generator more easily on a mobile device.

make calendar additional menu available for mobile

---

lib/contentful/search.ts
pages/search.tsx

This PR brings full show previews to search allows you to listen to a show directly from the search page without have to click into the individual show page. 📻 🎧 💜

Bugfix show preview search

---

util.ts

This PR fixes show artwork for shows that happen after midnight, ensuring that the artwork uses the previous date and colour.

adjust artwork for late shows

---

util.ts
yarn.lock

This fixes bug with show artwork incorrectly including an ampersand if only one new artist was submitted via the submission form.

Bugfix ampersand new artist

---

lib/contentful/calendar.ts
lib/contentful/pages/radio.ts
pages/admin/calendar.tsx

This PR adds a featured icon (🍊) in the calendar for shows that are in the featured section on the website.

Featured in calendar
